[tool.poetry]
name = "fmri-physio-log"
version = "0.2.0rc1"
description = "Parse Siemens PMU files"
authors = [
    "Andrew Ross <andrew.ross.mail@gmail.com>"
]
license = "MIT"

readme = "README.md"

homepage = "https://github.com/andrewrosss/fmri-physio-log"
repository = "https://github.com/andrewrosss/fmri-physio-log"
documentation = "https://github.com/andrewrosss/fmri-physio-log"

keywords = ["mri", "siemens", "pmu"]

classifiers = [
    "Programming Language :: Python :: 3.0",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
]

[tool.poetry.dependencies]
python = "^3.7"
pyparsing = "^3.0.7"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
flake8 = "^4.0.1"
pylint = "^2.12.2"
reorder-python-imports = "^2.7.1"
bump2version = "^1.0.1"
pre-commit = "^2.17.0"
pytest = "^7.0.1"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
